const express = require('express');
const router = express.Router();

const townsAndAreas = [
    {
        "town": "Nairobi",
        "county": "Nairobi County",
        "region": "Nairobi",
        "areas": [
          "Westlands",
          "Kilimani",
          "Lavington",
          "Karen",
          "Langata",
          "Eastleigh",
          "Embakasi",
          "Dagoretti",
          "Kasarani",
          "Kamukunji",
          "Starehe",
          "Makadara",
          "Kibra",
          "Parklands",
          "Highridge",
          "Gigiri",
          "Muthaiga",
          "Spring Valley",
          "Kitisuru",
          "Hurlingham",
          "Madaraka",
          "Umoja",
          "Kayole",
          "Dandora",
          "Roysambu",
          "Kahawa West",
          "Mwiki",
          "Donholm",
          "Komarock",
          "Imara Daima",
          "Syokimau",  // Technically outside Nairobi County but often considered part of the metro area
          "Mlolongo", // Technically outside Nairobi County but often considered part of the metro area
          "South B",
          "South C",
          "Kileleshwa",
          "Adams Arcade",
          "Woodley",
          "Loresho",
          "Kabete",
          "Kangemi",
          "Waithaka",
          "Riruta",
          "Satellite",
          "Embakasi Village",
          "Utawala",
          "Mihango",
          "Ruai",
          "Njiru",
          "Doonholm",
          "Buruburu",
          "Jericho",
          "Hamza",
          "Pangani",
          "Kawangware",
          "Dagoretti Corner",
          "Karen Hardy",
          "Langata Estate",
          "Nyayo Estate",
          "Embakasi East",
          "Embakasi West",
          "Embakasi North",
          "Embakasi South",
          "City Centre", // Nairobi CBD
          "Upper Hill",
          "Community",
          "Nairobi Hill",
          "Hill View",
          "Kenyatta National Hospital Area",
          "State House Area",
          "Milimani", // Also listed above, but important to note its proximity to CBD
          "Kariokor",
          "Shauri Moyo",
          "Pumwani",
          "Mathare",
          "Baba Dogo",
          "Kasipul",
          "Korogocho",
          "Kariobangi",
          "Dandora Phase 1",
          "Dandora Phase 2",
          "Dandora Phase 3",
          "Dandora Phase 4",
          "Dandora Phase 5",
          "Kayole 1",
          "Kayole 2",
          "Kayole 3",
          "Kayole 4",
          "Kayole 5",
          "Kayole 6",
          "Kayole 7",
          "Kayole 8",
          "Embakasi Central",
          "Embakasi South",
          "Embakasi North",
          "Embakasi East",
          "Embakasi West",
          "Ruaraka",
          "Kahawa Sukari",
          "Ruai",
          "Utawala",
          "Mihango",
          "Njiru",
          "Kamulu",
          "Joska",
          "Ngong Road",
          "Kiambu Road",
          "Limuru Road",
          "Mombasa Road",
          "Outer Ring Road",
          "Eastern Bypass"
        ]
    },
    {
        "town": "Mombasa",
        "county": "Mombasa County",
        "region": "Coast",
        "areas": [
          "Mombasa Island",
          "Nyali",
          "Kisauni",
          "Likoni",
          "Changamwe",
          "Jomvu",
          "Mtwapa",  // Often considered part of Mombasa metro area, but technically in Kilifi County
          "Bamburi",
          "Shanzu",
          "Kwale", // Technically in Kwale County
          "Diani", // Technically in Kwale County
          "Ukunda", // Technically in Kwale County
          "Kizingo",
          "Mkomani",
          "Ganjoni",
          "Majengo",
          "Tononoka",
          "Mvita",
          "Tudor",
          "Port Reitz",
          "Chaani",
          "Magongo",
          "Miritini",
          "Mikindani",
          "Junda",
          "Kikambala", // Technically in Kilifi County
          "Vipingo",  // Technically in Kilifi County
          "Mombasa CBD", // Central Business District
          "Fort Jesus Area",
          "Old Town",
          "Tusks Area",
          "Uhuru Gardens",
          "Moi International Airport Area",
          "Mombasa Port Area",
          "Kipevu",
          "Mkupe",
          "Shimanzi",
          "Railway Quarters",
          "Majengo Soko",
          "Mwembe Tayari",
          "Nassau",
          "Links Road",
          "Bamburi Cement Area",
          "Shanzu Beach",
          "Nyali Bridge Area",
          "Likoni Ferry Area",
          "Diani Beach",
          "Ukunda Airport Area",
          "Msambweni",
          "Lunga Lunga",
          "Kinango",
          "Samburu",
          "Matuga",
          "Kwale Town",
          "Galu",
          "Msambweni",
          "Vanga",
          "Shimoni",
          "Funzi Island"
        ]
    },
    {
        "town": "Nakuru",
        "county": "Nakuru County",
        "region": "Rift Valley",
        "areas": [
          "Nakuru Town West",
          "Nakuru Town East",
          "Bahati",
          "Rongai",
          "Gilgil",
          "Naivasha",
          "Lanet",
          "Menengai",
          "Kiamunyi",
          "Ngata",
          "Njoro",
          "Molo",
          "Biashara",
          "Industrial Area",
          "Milimani",
          "Nakuru CBD", // Central Business District
          "London",
          "Kivumbini",
          "Shaabab",
          "Nakuru North",
          "Nakuru South",
          "Subukia",
          "Bahati",
          "Rongai",
          "Gilgil",
          "Naivasha",
          "Mai Mahiu",
          "Elementaita",
          "Nakuru West",
          "Nakuru East",
          "Kaptembwa",
          "Racecourse",
          "Polyview",
          "Nakuru Hill",
          "Menengai Crater",
          "Lake Nakuru National Park",
          "Hyrax Hill",
          "Egerton University",
          "Kabarak University",
          "Solai",
          "Bahati Centre",
          "Rongai Centre",
          "Njoro Town",
          "Molo Town",
          "Kuresoi",
          "Oljororok",
          "Kinangop",
          "Mirugi Kariuki",
          "Kefafa",
          "Barut",
          "Kampi ya Moto",
          "Nessuit",
          "Mau Narok",
          "Soin",
          "Keringet",
          "Turi",
          "Elburgon",
          "Kipkabus",
          "Kibwezi",
          "Mweiga",
          "Subukia Valley",
          "Elementaita Town",
          "Gilgil Town"
        ]
      },
      {
        "town": "Ruiru",
        "county": "Kiambu County",
        "region": "Central",
        "areas": [
          "Ruiru Town",
          "Kahawa West",
          "Kahawa Sukari",
          "Zimmerman", // Sometimes considered part of Nairobi
          "Tala", // Often considered part of Nairobi's greater metropolitan area
          "Mwihoko", // Often considered part of Nairobi's greater metropolitan area
          "Githurai 45",
          "Githurai 44", // Often considered part of Nairobi's greater metropolitan area
          "Clay City", // Often considered part of Nairobi's greater metropolitan area
          "Kimbo",
          "Membley",
          "Ruiru East",
          "Ruiru West",
          "Githunguri",
          "Ruiru Kamakis",
          "Ruiru Bypass",
          "Ruiru Sports Club Area",
          "Eastern Bypass Area",
          "Greater Ruiru",
          "Ruiru Ridge",
          "Ruiru Golf Course Area",
          "Rainbow Ruiru",
          "Sunrise Ruiru",
          "Maringo",
          "Ngao",
          "Gitothua",
          "Kahawa Wendani",
          "Muthithi",
        ]
      },
]

router.get('/api/locations', (req, res) => {
  res.json(townsAndAreas);
});

module.exports = router;
